version: '2'

services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./scripts/dump-demo.sql:/docker-entrypoint-initdb.d/1.sql            # Load static-date 
      - ./scripts/update-datetimes.sql:/docker-entrypoint-initdb.d/2.sql             # Move date-times to today
      - ./scripts/performance-workaround.sql:/docker-entrypoint-initdb.d/3.sql  # Adds materialized views
      - ./scripts/search-index-rebuild.sql:/docker-entrypoint-initdb.d/4.sql        # Cause search index to rebuild

  web:
    build: web
    image: openmrscorecfl:8.0.0-public-demo
    depends_on:
      - db
    environment:
      DB_DATABASE: openmrs
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
      COPY_CFL_MODULES: 'false'
    ports:
      - "${TOMCAT_PORT}:8080"
    volumes:
      - ~/.cfl/reports:/usr/local/tomcat/.OpenMRS/reports
