version: '2'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: --path.procfs=/host/proc --path.rootfs=/rootfs --path.sysfs=/host/sys --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"

  prometheus-mysql-exporter:
    image: braedon/prometheus-mysql-exporter:0.5.0
    container_name: prometheus-mysql-exporter
    restart: always
    volumes:
      - ./monitoring/prometheus-mysql-exporter.cfg:/etc/prometheus-mysql-exporter.cfg
    command: -s db -P ${DB_ROOT_PASSWORD} -c /etc/prometheus-mysql-exporter.cfg
    ports:
      - "9207:9207"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.enable-lifecycle
    ports:
      - "9090:9090"
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    depends_on:
      - node-exporter
      - prometheus-mysql-exporter
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
